### ISSUE TITLE
Problems trying to get the unit tests to run

### ISSUE THREAD

**Issue by alethcoe** [boozallen/sdp-libraries#103]
I was trying to get Unit Testing working on my own fork and ran into an issue. So I decided to fork your tests and run them locally to see if I could figure out what was wrong but ran into the same issue. 

So i pulled down the latest today of the master branch, then ran from my windows computer using Docker for Windows set to linux your tests.

The command from powershell looked like 
```docker run -v ${PWD}:/app -w/app gradle:6.3.0-jdk8 gradle --no-daemon test```
basically the same command as in the make file.

```
FAILURE: Build failed with an exception.

* Where:
Build file '/app/build.gradle' line: 2

* What went wrong:
Plugin [id: 'org.jenkins-ci.jpi', version: '0.38.0'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (could not resolve plugin artifact 'org.jenkins-ci.jpi:org.jenkins-ci.jpi.gradle.plugin:0.38.0')
  Searched in the following repositories:
    Gradle Central Plugin Repository
```

Am I doing something wrong or is there a bigger problem here.

**Comment by steven-terrana** [comment]
Hey @alethcoe - we've just merged some changes that resolved some issues with the unit tests. 

If you run `./gradlew clean test` after fetching the latest changes it ought to work

can you give that a try please?
