### ISSUE TITLE
How to use implement detect change with monorepo?

### ISSUE THREAD

**Issue by namcxn** [boozallen/sdp-libraries#126]
Hi team,

Any idea support detect change with monorepo when use sap-libraries?

Thank.

**Comment by cokieffebah** [comment]
Are asking how to detect changes in a git repository?  if so, most users simply check for changes on a branch using https://github.com/boozallen/sdp-libraries/tree/main/libraries/git/steps  our on_* steps in a pipeline template/Jenkinsfile

```
on_merge to: 'main' {
   build_app()
   unit_test()
   email_team()
}
```
